### ISSUE TITLE
Invalid README link

### ISSUE THREAD

**Issue by john-h-k** [flyingdevelopmentstudio/infiniteflight-api#10]
> Other Aircraft
These docs may be updated with information about other aircraft. [More information can be found on the Infinite Flight Community forum API category](https://community.infiniteflight.com/c/thirdparty/api/40).

The link is a 404

**Comment by Brandon1419** [comment]
Not exactly an issue... It links to a private category on the forum for developers using the API. You can PM Cam on the forum with your idea and I’m sure he’ll be more than happy to add you to the category. :)
